import Head from "next/head";

import { useRouter } from "next/router";
import { SubmitHandler, useForm } from 'react-hook-form';
import { api } from "../services/api";

type FormData = {
  name: string,
  username: string
}

export default function Cadastro(){

  const router = useRouter()
  const { register, handleSubmit } = useForm<FormData>()

  const onSubmit: SubmitHandler<FormData> = async ({ name, username }) => {
    await api.post('/users', { name, username })
    router.push('/')
  }

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form onSubmit={handleSubmit(onSubmit)}>
          <div>
            <input type="text" id="name" {...register('name')}/>
            <input type="text" id="username" {...register('username')}/>
          </div>
          <button type="submit">Adicionar</button>
        </form>
      </main>
    </>
  )
}