import { User } from '@prisma/client'
import { GetStaticProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Users from '../components/Users'
import { getUsers } from '../lib/users'

type Props = {
  users : User[]
}

export const getStaticProps: GetStaticProps = async () => {

  const users = await getUsers()
  
  return {
    props: {
      users,
    },
    revalidate: 60
  }
}

export default function Home({ users }: Props) {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>Usuarios cadastrados no banco</h1>
          <Link href={'/cadastro'}>Adicionar novo usuario</Link>
        </div>
        {!!users && (<Users users={users}/>)}
      </main>
    </>
  )
}
