import { User } from '@prisma/client'
import { GetStaticProps } from 'next'
import Head from 'next/head'
import { getUsers } from '../lib/users'


type Props = {
  users : User[]
}


export const getStaticProps: GetStaticProps = async () => {

  const users = await getUsers()
  
  return {
    props: {
      users,
    },
    revalidate: 60
  }
}


export default function Home({ users }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Usuarios cadastrados no banco</h1>
        <div>
          <ul>
            {!!users && users.map(user => (
              <li key={user.id}>
                <p>@{user.username}: <span>{user.name}</span></p>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  )
}
